### PR TITLE
Kinesis route and event creation

### PR DESCRIPTION
**Pull request by yuenmichelle1**
Kinesis Route and Different Events creation on kinesis ingest. 
- Rspec Setup and specs for kinesis controller and event creation
- Update session_time to be decimal type for precision

### CODE REVIEW

**Review by zwolf — COMMENTED** [review]
Are you planning on using ActiveInteraction when developing the rest of Eras? If not, it’s a lot of overhead for just this one single action. If so, I’m curious about what makes the service object pattern and the additional complexity (of the gem and DSL) a good fit here. I’m personally partial to the way that Caesar does this: just a `/kinesis` endpoint and a KinesisStream PORO that loops the payload along to the processor. If you’re going all in on ActiveInteraction, this makes sense to start with—I just want to clarify whether or not that’s the intention.

Not for this PR, but it’s probably a good idea to set up the kind of basic auth that Caesar and Designator have on their API endpoints eventually. Not that anyone’s flinging forged classifications at us, but it’s a good practice we can come back around to.

**Comment by yuenmichelle1** [comment]
The more I mull it over, I agree that active-interaction is not needed. As much as I like it and the idea of operations(personal preference), we possibly are not benefitting from everything active_interaction and command architecture has to offer. I mainly used it to follow suit of the architecture of our previous apps (panoptes, education-api, etc). But knowing more of the history behind those apps, this architecture was briefly adopted and left on the wayside. 

I converted this back to draft while I work through specs. A lot of the logic and cleanup will be the same but in this case this rewrite is to accommodate not using active_interaction and operation.

**Review by zwolf — APPROVED** [review]
LGTM! I like the refactor, esp the StreamEvent models. FYI I put up a PR to add running specs in CI in case you want to review/merge that first so that all these tests can run.

**Comment by yuenmichelle1** [comment]
> FYI I put up a PR to add running specs in CI in case you want to review/merge that first so that all these tests can run.

👍 Thanks!

**Pull request merged**
